apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking-backend-ingress
  namespace: banking
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.bank.example.com
      secretName: banking-api-tls
  rules:
    - host: api.bank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banking-backend-service
                port:
                  number: 80
