apiVersion: v1
kind: Service
metadata:
  name: banking-backend-service
  namespace: banking
spec:
  selector:
    app: banking-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
