---
- name: Configure Kubernetes nodes
  hosts: k8s_cluster
  become: true
  roles:
    - common

- name: Configure Kubernetes master
  hosts: master
  become: true
  roles:
    - k8s_master

- name: Configure Kubernetes workers
  hosts: workers
  become: true
  roles:
    - k8s_worker
